### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by d3v3lop3rDE** [jgosmann/mh-z19c#1]
Hello,

could you please provide a more detailed example and the used UART implementation?
Currently Iam using the rppal_w_frontend Library for the Uart Connection (which uses linux-embedded-hal as backend). 
So Iam expieriencing errors:
`106 |     let mut sensor = MhZ19C::new(uart);
    |                      ^^^^^^^^^^^^^^^^^ the trait `embedded_hal::serial::Write<u8>` is not implemented for `Uart`
`
Thank you!

**Comment by jgosmann** [comment]
Did you enable the `hal` feature? (cp. [documentation](https://docs.rs/rppal_w_frontend/0.0.4/rppal_w_frontend/uart/struct.Uart.html))

**Comment by jgosmann** [comment]
Also cp. [here](https://github.com/jgosmann/rpi-mh-z19c-exporter/blob/main/Cargo.toml#L23) and [here](https://github.com/jgosmann/rpi-mh-z19c-exporter/blob/main/src/main.rs#L68)

**Comment by jgosmann** [comment]
Closing this as stale, feel free to reopen if you still have an issue.
